# error 进程池

```sh
AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'
```

https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function


https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled


## python  async await

https://stackabuse.com/python-async-await-tutorial/


https://stackoverflow.com/questions/41816973/modulenotfounderror-what-does-it-mean-main-is-not-a-package


http://www.langzi.fun/Asyncio%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B.html

> ERROR:asyncio:Task exception was never retrieved future

https://stackoverflow.com/questions/46890646/asyncio-weirdness-of-task-exception-was-never-retrieved

> async AttributeError: __aexit__

https://www.docs4dev.com/docs/zh/python/3.7.2rc1/all/reference-datamodel.html


## windows python 协程

error
```sh
AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'run_in_excutor'
```

https://stackoverflow.com/questions/48555439/share-async-await-coroutine-based-complex-object-across-multiprocess

https://docs.python.org/3.7/library/asyncio-task.html



### python 3.6 error

```sh
AttributeError: 'CoroWrapper' object has no attribute 'result'


{'gen': <coroutine object _download_report at 0x7f9eeac9e678>, 'func': None, '_source_traceback': [<FrameSummary file /opt/webeye/hedwig/src/admin/webeye/management/commands/app_alarm.py, line 141 in crawl_manager>, <FrameSummary file /opt/webeye/hedwig/src/admin/webeye/management/commands/app_alarm.py, line 50 in crawl_task>, <FrameSummary file /usr/lib64/python3.6/asyncio/base_events.py, line 460 in run_until_complete>, <FrameSummary file /usr/lib64/python3.6/asyncio/base_events.py, line 427 in run_forever>, <FrameSummary file /usr/lib64/python3.6/asyncio/base_events.py, line 1432 in _run_once>, <FrameSummary file /usr/lib64/python3.6/asyncio/events.py, line 145 in _run>, <FrameSummary file /opt/webeye/hedwig/src/admin/webeye/management/commands/app_alarm.py, line 65 in crawl_job>, <FrameSummary file /opt/webeye/hedwig/src/admin/.venv/lib/python3.6/site-packages/retrying.py, line 49 in wrapped_f>, <FrameSummary file /opt/webeye/hedwig/src/admin/.venv/lib/python3.6/site-packages/retrying.py, line 200 in call>, <FrameSummary file /usr/lib64/python3.6/asyncio/coroutines.py, line 85 in debug_wrapper>], '__name__': '_download_report', '__qualname__': '_download_report'}
```

https://stackoverflow.com/questions/48625933/python-async-attributeerror-aexit



## python3.6 pickle

https://stackoverflow.com/questions/28963354/typeerror-cant-pickle-generator-objects
https://stackoverflow.com/questions/43124340/python-3-6-coroutine-was-never-awaited

https://www.blog.pythonlibrary.org/2016/07/26/python-3-an-intro-to-asyncio/

https://stackoverflow.com/questions/51680178/asyncio-create-task-vs-await


## python csv BOM code

https://code-examples.net/en/q/11ccd08

http://farmdev.com/talks/unicode/


## RecursionError: maximum recursion depth exceeded while calling a Python object

https://stackoverflow.com/questions/6809402/python-maximum-recursion-depth-exceeded-while-calling-a-python-object

https://stackoverflow.com/questions/12047847/super-object-not-calling-getattr

## __getattr__

https://www.cnblogs.com/xybaby/p/6280313.html


## 65192 Task was destroyed but it is pending!
https://stackoverflow.com/questions/33505066/python3-asyncio-task-was-destroyed-but-it-is-pending-with-some-specific-condit


https://stackoverflow.com/questions/27402796/multiple-loops-with-asyncio


GCP 9 10 2天数据
